Repository octokit/core.js, pull requests merged in 2020-06, with the labels that each got.

#87 Add CodeQL security scanning
  .github/workflows/codeql.yml
Labels: maintenance

#101 remove deprecated APIs
  src/index.ts
  test/__snapshots__/plugin.test.ts.snap
  test/auth.test.ts
  test/plugin.test.ts
Labels: feature

#103 Fix grammar in README
  README.md
Labels: bug

#108 feat: `Octokit.defaults()` accepts callback function
  README.md
  src/index.ts
  test/defaults.test.ts
Labels: feature
