Repository octokit/core.js, pull requests merged in 2020-08, with the labels that each got.

#153 docs(README): `plugin-throttle` should be `plugin-throttling`, `plugin-paginate` should be `plugin-paginate-rest`
  README.md
Labels: bug, documentation

#150 Add missing types for `OctokitOptions`
  src/types.ts
Labels: bug, typescript

#154 Fix authentication anchor reference
  README.md
Labels: bug, documentation

#168 chore: spelling: registered
  src/index.ts
Labels: maintenance
