Repository octokit/core.js, pull requests merged in 2020-10, with the labels that each got.

#216 test: add `issues.test.ts` as a place to put tests if it is unclear where else to put them
  CONTRIBUTING.md
  test/issues.test.ts
Labels: maintenance

#217 docs(ISSUE_TEMPLATES): bug/feature issue template and a link to the discussion forum on @octokit/rest.js
  .github/ISSUE_TEMPLATE/01_bug.md
  .github/ISSUE_TEMPLATE/02_feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: maintenance

#221 fix: use correct URL to create installation access token for `octokit.graphql()` and GHES
  src/index.ts
  test/auth.test.ts
Labels: bug

#226 fix: pass through logger to @octokit/auth-app
  package-lock.json
  src/index.ts
  test/auth.test.ts
Labels: bug

#233 feat(auth): pass `octokit` and `octokitOptions` to `options.authStrategy`
  src/index.ts
  test/auth.test.ts
Labels: feature

#236 fix(README): rename `id` to `appId` in usage example
  README.md
Labels: bug, documentation
