Repository octokit/core.js, pull requests merged in 2021-06, with the labels that each got.

#355 feat: `error.response`
  README.md
  package-lock.json
  package.json
Labels: feature

#356 fix(typescript): avoid the `void`
  src/types.ts
  test/typescript-validate.ts
Labels: bug, typescript

#357 test(graphql): custom headers
  test/graphql.test.ts
Labels: maintenance

#358 docs: fix @octokit/action-auth
  README.md
Labels: bug, documentation
